---
MASKED_PARAMETER_CLASSES:
  - 'com.michelin.cio.hudson.plugins.passwordparam.PasswordParameterDefinition'
  - 'hudson.model.PasswordParameterDefinition'
NAME_PASSWORD_PAIRS:
  - NAME: 'testName'
    PASSWORD: 'password1'
