from unittest import TestCase

from jenkinsapi.jenkins import Jenkins

class PluginTestCase(TestCase):

    def setUp(self):
        self.jenkins = Jenkins("http://localhost:8080")
        self.plugins = self.jenkins.get_plugins()

    def test_sample_plugins_installed(self):
        installed_plugin_versions = {
                value.shortName: value.version
                for _, value in self.plugins.iteritems()
                }
        expected_plugin_versions = {
            "PrioritySorter": "2.9",
            "ace-editor": "1.0.1",
            "ansicolor": "0.4.1",
            "ant": "1.8",
            "antisamy-markup-formatter": "1.3",
            "apache-httpcomponents-client-4-api": "4.5.3",
            "authentication-tokens": "1.1",
            "bouncycastle-api": "2.16.0",
            "branch-api": "2.0.7",
            "build-flow-plugin": "0.20",
            "build-flow-test-aggregator": "1.0",
            "build-flow-toolbox-plugin": "0.1",
            "build-name-setter": "1.3",
            "build-timeout": "1.19",
            "build-user-vars-plugin": "1.5",
            "buildgraph-view": "1.1.1",
            "cloudbees-folder": "5.18",
            "cobertura": "1.11",
            "conditional-buildstep": "1.3.1",
            "copyartifact": "1.39",
            "credentials-binding": "1.15",
            "credentials": "2.1.16",
            "cvs": "2.14",
            "display-url-api": "2.0",
            "docker-commons": "1.5",
            "docker-workflow": "1.14",
            "durable-task": "1.14",
            "ec2": "1.28",
            "envinject-api": "1.3",
            "envinject": "2.1.5",
            "exclusive-execution": "0.8",
            "external-monitor-job": "1.4",
            "flexible-publish": "0.",15.2",
            "ghprb": "1.36.0",
            "git-client": "2.7.0",
            "git-server": "1.7",
            "git": "3.8.0",
            "github-api": "1.90",
            "github-branch-source": "2.3.3",
            "github-oauth": "0.29",
            "github": "1.28.1",
            "gradle": "1.24",
            "groovy-postbuild": "2.3.1",
            "groovy": "2.0",
            "handlebars": "1.1",
            "hipchat": "0.1.9",
            "hockeyapp": "1.2.2",
            "htmlpublisher": "1.10",
            "icon-shim": "2.0.3",
            "jackson2-api": "2.7.3",
            "javadoc": "1.3",
            "job-dsl": "1.47",
            "jobConfigHistory": "2.10",
            "jquery-detached": "1.2.1",
            "jquery": "1.7.2",
            "jsch": "0.1.54.2",
            "junit": "1.24",
            "ldap": "1.20",
            "mailer": "1.21",
            "mapdb-api": "1.0.1.0",
            "mask-passwords": "2.10.1",
            "matrix-auth": "1.5",
            "matrix-project": "1.7.1",
            "maven-plugin": "3.1",
            "momentjs": "1.1",
            "monitoring": "1.71.0",
            "multiple-scms": "0.6",
            "node-iterator-api": "1.1",
            "nodelabelparameter": "1.7.2",
            "pam-auth": "1.2",
            "parameterized-trigger": "2.35.2",
            "pipeline-build-step": "2.4",
            "pipeline-graph-analysis": "1.1",
            "pipeline-input-step": "2.8",
            "pipeline-milestone-step": "1.3",
            "pipeline-model-api": "1.2.9",
            "pipeline-model-declarative-agent": "1.1.1",
            "pipeline-model-definition": "1.2.9",
            "pipeline-model-extensions": "1.2.9",
            "pipeline-rest-api": "2.4",
            "pipeline-stage-step": "2.3",
            "pipeline-stage-tags-metadata": "1.2.9",
            "pipeline-stage-view": "2.4",
            "plain-credentials": "1.3",
            "rebuild": "1.25",
            "run-condition": "1.0",
            "scm-api": "2.2.6",
            "script-security": "1.42",
            "shiningpanda": "0.21",
            "splunk-devops": "1.6.4",
            "ssh-agent": "1.14",
            "ssh-credentials": "1.13",
            "ssh-slaves": "1.26",
            "structs": "1.14",
            "subversion": "2.10.3",
            "text-finder": "1.10",
            "thinBackup": "1.7.4",
            "timestamper": "1.8.9",
            "token-macro": "2.3",
            "translation": "1.16",
            "violations": "0.7.11",
            "windows-slaves": "1.3.1",
            "workflow-aggregator": "2.5",
            "workflow-api": "2.25",
            "workflow-basic-steps": "2.6",
            "workflow-cps-global-lib": "2.9",
            "workflow-cps": "2.46",
            "workflow-durable-task-step": "2.15",
            "workflow-job": "2.11",
            "workflow-multibranch": "2.16",
            "workflow-scm-step": "2.5",
            "workflow-step-api": "2.14",
            "workflow-support": "2.18",
            "xunit": "1.93"
        }
        for plugin, version in installed_plugin_versions.iteritems():
            print "Checking if {} at version {} is installed".format(
                    plugin, installed_plugin_versions[plugin])
            assert expected_plugin_versions[plugin] == version
